### ISSUE TITLE
i use systemd but no *net* service

### ISSUE THREAD

**Issue by marceltransier** [rpuntaie/mutt-wizard#10]
https://github.com/rpuntaie/mailwizard/blob/a6d2522358435b3d28547fc75910f0458fc168af/bin/mw#L78-L81

these lines prevent me from running this script even though i do have a working internet connection

**Comment by rpuntaie** [comment]
Thanks. I will use another solution, e.g. on of these
https://unix.stackexchange.com/questions/190513/shell-scripting-proper-way-to-check-for-internet-connectivity
