### ISSUE TITLE
"msync -a" complains "IMAP command 'CREATE "..."' returned an error: NO CREATE Folder exist"

### ISSUE THREAD

**Issue by bon-ami** [rpuntaie/mutt-wizard#11]
ubuntu 18.04 within LAN and not using a sudo user.
with mw manually downloaded and extracted, and neomutt and other debs downloaded and extracted under ~/.local
"mw -a" finishes w/o errors. then I want to "msync -a" to download my mails (otherwise I cannot see anything in neomutt?)
but it says "C: 0/1  B: 10/11  M: +0/0 *0/0 #0/0  S: +0/0 *0/0 #0/0" and "IMAP command 'CREATE "..."' returned an error: NO CREATE Folder exist" with all my folders on mail server.
I wonder whether mw did not config isync correctly or I should report this to isync.
Thank you.

I replaced my home dir with ${HOME} and changed my mail addr to ${MAIL} within following settings here. only a part of each setting is provided.
```
       │ File: .config/mutt/muttrc
   1   │ # vim: filetype=neomuttrc
   2   │ #source /usr/local/share/mutt-wizard/mutt-wizard.muttrc
   3   │ source ${HOME}/.local/share/mutt-wizard.muttrc
   4   │ source ${HOME}/.config/mutt/accounts/${MAIL}@126.com.muttrc
```
```
       │ File: .config/mutt/accounts/${MAIL}@126.com.muttrc
   7   │ set folder = "${HOME}/.local/share/mail/${MAIL}@126.com"
   8   │ set header_cache = "${HOME}/.cache/mutt-wizard/${MAIL}_126.com/headers"
   9   │ set message_cachedir = "${HOME}/.cache/mutt-wizard/${MAIL}_126.com/bodies"
  10   │ set mbox_type = Maildir
  11   │ set hostname = "126.com"
  12   │ source ${HOME}/.local/share/switch.muttrc
```
```
       │ File: .mbsyncrc
   1   │ IMAPStore ${MAIL}@126.com-remote
   4   │ User ${MAIL}@126.com
   5   │ PassCmd "pass ${MAIL}@126.com"
   6   │ AuthMechs LOGIN
   7   │ SSLType IMAPS
   8   │ CertificateFile /etc/ssl/certs/ca-certificates.crt
   9   │
  10   │ MaildirStore ${MAIL}@126.com-local
  11   │ Subfolders Verbatim
  12   │ Path ${HOME}/.local/share/mail/${MAIL}@126.com/
  13   │ Inbox ${HOME}/.local/share/mail/${MAIL}@126.com/INBOX
  14   │
  15   │ Channel ${MAIL}@126.com
  16   │ Expunge Both
  17   │ Master :${MAIL}@126.com-remote:
  18   │ Slave :${MAIL}@126.com-local:
  19   │ Patterns * !"[Gmail]/All Mail" !"*fts-flatcurve*" !"*virtual*"
```

**Comment by bon-ami** [comment]
a same issue was reported to Isync https://sourceforge.net/p/isync/bugs/69/
then my question here is whether after creating an account with `mw -a`, do I have to call `msync -a` before `neomutt` can get mails.

**Comment by rpuntaie** [comment]
`mailwizard` just sets up the config.
It sets up `mbsync`, if it is there, else uses `getmail`.

I don't use the `mbsync` command from [isync](https://isync.sourceforge.io/).
I use [getmail6](https://github.com/getmail6/getmail6).

Both `getmail` and `mbsync` fetch mail by themselves, without mutt.
I use mutt just to view the mail.

It seem your problem is one with `mbsync`.
I cannot help you with that.
