### ISSUE TITLE
consider tagging the versions ?

### ISSUE THREAD

**Issue by Kr1ss-XD** [rpuntaie/mutt-wizard#2]
Hi @rpuntaie !

Your project is now [packaged in the AUR](https://aur.archlinux.org/packages/mailwizard-git/).

I noticed that you've introduced versioning in your fork, which I appreciate. If you'd provide tags, we could take advantage of them and use them in the AUR package versions too.

On top of the tag system, Github supports hosting release tarballs. If you're interested, you could provide e.g. `mailwizard 2.0` as a release, then I'd push a stable package in addition to the '`-git`' one. This would enable users to choose if they install fixed versions or rather be on the bleeding edge and go with the development package.

Btw the documentation is great, and I like that you added a test environment. :smile:

**Comment by rpuntaie** [comment]
I tagged and made a release.
Thanks for suggesting.

**Comment by Kr1ss-XD** [comment]
Great, thank you !

https://aur.archlinux.org/packages/mailwizard/
