### ISSUE TITLE
Opening GMail Trash closes neomutt

### ISSUE THREAD

**Issue by kronikpillow** [rpuntaie/mutt-wizard#5]
when trying to open GMail Trash neomutt unexpectedly closes

**Comment by rpuntaie** [comment]
This seems more like a `neomutt` issue.

**Comment by kronikpillow** [comment]
I would disagree, works perfectly fine on mutt-wizard

**Comment by rpuntaie** [comment]
I tried it. No crash.

Maybe it is related to #3.

Check your configs, whether you still have ``mutt-wizard`` entries, especially muttrc.

**Comment by kronikpillow** [comment]
hm ... no, I have 2 separate hdds, one is a full LARBS setup with Luke's defaults, it's a system i learned to use and am partially accustomed to (I'm a linux user for 6-7 months, out of which I use larbs for 2), the 2nd hdd is my own i3, where I'm building my own setup of the entire system from scratch, basically a trial and error system where I can afford to crash my system and just switch to LARBS i3 without having to reinstall or timeshift everything straight away, on my system i tried your mailwizard because i found your comment on the mutt-wizard-git AUR package and wanted to try it out and see the differences ...  I will reproduce my steps to the error and get back to you as soon as I can .. 

do I need some specific environment variables set?

**Comment by rpuntaie** [comment]
No
