### ISSUE TITLE
invalid argument for mailboxes command

### ISSUE THREAD

**Issue by jeLee6gi** [rpuntaie/mutt-wizard#6]
neomutt complains about the mailboxes command created by mailwizard. For example in the configuration of my first account ```~/.config/mutt/accounts/1-name@example.com.mwonofftype.offline.muttrc```, mailwizard put

```
mailboxes =name_example_com ===================== "=Drafts" "=Sent" "=Trash" "=INBOX" "=Queue" "=Archive" "=Junk"
```

Which causes the following errors when starting neomutt

```
Unknown Mailbox: /home/name/mail/name@example.com/name_example_com
Error in /home/name/.config/mutt/accounts/1-name@example.com.mwonofftype.offline.muttrc, line 21:
Error in /home/name/.config/mutt/mw_gen_mutt_accounts.muttrc, line 6: source: file /home/name/.config/mutt/accounts/1-name@example.com.mwonofftype.offline.muttrc could not be sourced
```

Deleting the first two arguments fixes the error, but of course `mw` puts them back every time I run it. Could you tell me how this was intended to work?

**Comment by rpuntaie** [comment]
The first 2 arguments were meant as header in the sidebar.
In summer 2019 that worked. The tests didn't show an error. I would have noticed.
I had noticed an error later in autumn on the machine where I use mutt,
but was busy with other things.
Now I've removed the first two arguments.
Thanks for reporting.
